version: '3'

services:
  web:
    env_file: env.txt   # Change env_sample.txt to env.txt
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  db:
      container_name: postgres
      image: mdillon/postgis:11-alpine
      env_file: .env_postgres
      volumes:
        - ./postgres-data:/var/lib/postgresql/data






# For db config read README.md/## Postgresql